# Generated by Django 5.1.6 on 2025-03-06 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=200, null=True, unique=True)),
                ('Password', models.CharField(max_length=150)),
            ],
        ),
    ]
