# Generated by Django 5.1.6 on 2025-03-06 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=170, null=True, unique=True)),
                ('Email', models.EmailField(max_length=120, null=True, unique=True)),
                ('Password', models.CharField(max_length=50, null=True)),
                ('Confirm_Password', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
