# Generated by Django 5.1.6 on 2025-03-06 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0002_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='Confirm_Password',
        ),
    ]
