# Generated by Django 5.1.6 on 2025-03-06 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0004_signup_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='Full_name',
            new_name='full_name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='Username',
            new_name='username',
        ),
    ]
