# Generated by Django 5.1.6 on 2025-03-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0005_rename_email_signup_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=200, null=True, unique=True)),
                ('Name', models.CharField(max_length=200, null=True, unique=True)),
                ('Password', models.CharField(max_length=150)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
