# Generated by Django 5.1.6 on 2025-03-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0006_user_delete_login_delete_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Name',
            new_name='Username',
        ),
    ]
