# Generated by Django 5.1.6 on 2025-03-07 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0007_rename_name_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
    ]
